# Welcome to Jekyll!

title: "Dr. David Castaño Internist in Medellín, Colombia"
email: dcastanosorio87@gmail.com
description: >- 
  I am an internist specialist in adult and elderly medicine services in Medellín. I am a native English speaker with extensive experience in managing adult and elderly patient pathologies. My services include:

baseurl: "/webpage" # the subpath of your site
url: "https://dcastano2024.github.io"
twitter_username: Drcastano
github_username: DCastano2024
markdown: kramdown

# Language settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      permalink: /:categories/:title/

  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
      permalink: /es/:categories/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed

contact:
  email: dcastanosorio87@gmail.com
  phone: "+57 3043807052"
  address: "Ciudad del Río, Medellín, Colombia"

paths:
  images: assets/images

# Ensure posts are included
collections:
  posts:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
